apiVersion: v1
kind: ConfigMap
metadata:
  name: cyclonedds-config
  namespace: default
data:
  cyclonedds.xml: |
    <CycloneDDS>
      <Domain id="0">
        <General>
          <AllowMulticast>false</AllowMulticast>
          <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
        </General>
        <Discovery>
          <Peers>
            <!-- Put the LAN IPs of machines that will run ROS 2 participants -->
            <Peer address="192.168.50.22"/>
            <Peer address="192.168.50.29"/>
            <Peer address="192.168.50.48"/>
            <Peer address="192.168.50.140"/>
          </Peers>
        </Discovery>
      </Domain>
    </CycloneDDS>